### ISSUE TITLE
 https://embeddings.gh-issue-labeler.com is down.

### ISSUE THREAD

**Issue by k4rth33k** [kubeflow/code-intelligence#127]
The site mentioned in the README.md of flask_app directory is not working.

**Comment by jlewi** [comment]
Thanks @k4rth33k ; I'm not sure we want to continue to maintain that site as a publicly available endpoint. So might make sense to update the README to not refer to it.

/cc @hamelsmu

**Comment by k4rth33k** [comment]
Ok. Thanks @jlewi
