### ISSUE TITLE
Confusion with dependencies when you have top level python utilities

### ISSUE THREAD

**Issue by hamelsmu** [kubeflow/code-intelligence#24]
We are sharing libraries in /py

However, each module may have different dependencies.  For example, the dependencies for my application may conflict with the dependencies for /py/code_intelligence.   

In this case, might be easier to break out each application into separate repositories so dependencies can be managed more cleanly.

Thoughts? Maybe there is another way of organizing that I haven't considered.  @jlewi

**Comment by jlewi** [comment]
How do we share code?

Can we resolve the dependency conflicts; i.e. find a common set of dependencies?

**Comment by hamelsmu** [comment]
options:
  - separate repo built as python module that can install via pip (pip install https://github...) with applications in their own repo
  - refactor utilities out of other folders into py but do work to make sure no dependencies conflict which they already are.  For example I’m using python 3.7 not sure if f-strings will work on version y’all are running 
  - wait until we encounter an issue then worry about it

Some existing projects in this repo have their own dependencies that already conflict with each other, that I’m not sure it makes sense to conform .  For example issue label v1 vs embedding have a significant number of non overlapping dependencies.

I’m a bit in favor of the first bullet but I’m flexible just wanted to raise this as I see some issues

**Comment by hamelsmu** [comment]
Also, I think it makes sense for any changes we make to the existing issue bot in production to be reflected back into the main repository at https://github.com/machine-learning-apps/Issue-Label-Bot and not only in this fork, as readers of the blog and other links point to that as the production repository (for example if someone wants to see the production code).

Even though we forked this repository from there, the nature of this repository is now significantly different than the original fork where a pull request back into the main one from this repository no longer makes any sense because this repo is a monolith of many different projects.

So, in summary, this is a proposal (which I'm flexible on if this doesn't suit somebody). 

- Delete IssueLabelBotv1 from this repo
- Clean this repo up so it is no longer a fork and doesn't have an upstream link to Issue Label Bot because this repo is now a collection of many projects.  Involves creating a new repository with the same name and copying everything over. 
- going forward, lets abstract all of all utils into /py in this repo, but leave any existing utllities that we have in our applications there because we probably don't have time to refactor and troubleshoot the dependency collisions right now.  going forward let's write tests for these so we can more easily manage the environment.  

Let me know if that sounds reasonable

**Comment by hamelsmu** [comment]
I changed my mind and updated comments so please read this issue directly instead of your email.  Thanks

**Comment by hamelsmu** [comment]
I went ahead and made the suggested changes as it didn't really touch anyone's code and only slightly changed the layout of the repo.  We can address the forked nature of this repo at another time it is not critical

**Comment by hamelsmu** [comment]
This issue is more or less resolved.  closing

**Comment by hamelsmu** [comment]
duplicate of https://github.com/kubeflow/code-intelligence/issues/29
