### ISSUE TITLE
Code organization for python module imports

### ISSUE THREAD

**Issue by abcdefgs0324** [kubeflow/code-intelligence#29]
- Should be very clear about what's a top level python package
- Always use absolute imports including unit tests
- Tell people what modules are top level python packages and expect them to set it appropriately
- Handle the situation that Python may disallow dashes in package names, i.e., `Label-Microservice`

**Comment by hamelsmu** [comment]
I agree thanks for putting this down.  I've been bad at following these rules of thumb

**Comment by hamelsmu** [comment]
Referencing this comment: https://github.com/kubeflow/code-intelligence/pull/34#issuecomment-520102842

**Comment by hamelsmu** [comment]
ok I'm consolidating everything into one issue:

1. Moving the notebook in /py  https://github.com/kubeflow/code-intelligence/issues/36
2. confusion with dependency management https://github.com/kubeflow/code-intelligence/issues/24
3. https://github.com/kubeflow/code-intelligence/pull/34 where we disucss this as well
