### ISSUE TITLE
Install Triage GitHub Action on Kubeflow Repos

### ISSUE THREAD

**Issue by jlewi** [kubeflow/code-intelligence#61]
Opening this issue to track using the new GitHub action to run our triage script in response to changes to an issue.

Some changes to the Kubeflow Infra

* Created service account github_actions and uploaded the GCP SA as a GitHub secret

   * This will be used by the action to push containers to gcr.io/kubeflow-ci

* Uploaded a personal access token for the github kubeflow-bot account to be used by the GitHub action

Related to: kubeflow/community#/278 - triage process
Related to: #59 define the GitHub action

**Comment by hamelsmu** [comment]
@jlewi this issue triggered this: https://github.com/kubeflow/code-intelligence/commit/ecbab8b8ca38ce8175c0a2550ab2a916e14d0e1d/checks?check_suite_id=328290064#step:3:9 after the latest workflow.  Does it look correct to you?

**Comment by jlewi** [comment]
It looks like the script ran successfully

```
INFO|2019-11-25T21:10:10|Triaging issue 61 - https://github.com/kubeflow/code-intelligence/issues/61|/py/issue_triage/triage_for_action.py|22|
INFO|2019-11-25T21:10:11|Issue https://github.com/kubeflow/code-intelligence/issues/61:
state:Issue doesn't need attention.
|/py/issue_triage/triage.py|678|
INFO|2019-11-25T21:10:11|None|/py/issue_triage/triage_for_action.py|24|
```

But the output doesn't look correct. The issue doesn't have a priority and therefore should need triage and the script should have added it to the triage kanban board.

I'm going to try retriggering it by removing the kind label.

**Comment by jlewi** [comment]
This is fixed.

See kubeflow/community#306
